### ISSUE TITLE
Cannot run redshift-gtk

### ISSUE THREAD

**Issue by anku94** [jonls/redshift#179]
I seem to get the following error while running redshift-gtk (Redshift works great). I'm using Linux Mint 17, 64 bit with Cinnamon.

```bash
~ ❯❯❯ redshift-gtk
Traceback (most recent call last):
  File "/usr/bin/redshift-gtk", line 26, in <module>
    from redshift_gtk.statusicon import run
  File "/usr/lib/python3.4/site-packages/redshift_gtk/statusicon.py", line 31, in <module>
    from gi.repository import Gtk, GLib
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 36, in <module>
    from ._gi import _gobject
ImportError: /usr/lib/python2.7/dist-packages/gi/_gi.so: undefined symbol: _Py_ZeroStruct
~ ❯❯❯ echo $PYTHONPATH                                                                                                                                                
/usr/lib/python2.7/dist-packages
~ ❯❯❯ python --version
Python 2.7.6
~ ❯❯❯ python3 --version
Python 3.4.0
```

Versions of some of the basic packages:

```
python-gobject:
  Installed: 3.12.0-1ubuntu1
  Candidate: 3.12.0-1ubuntu1
  Version table:
 *** 3.12.0-1ubuntu1 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.12.0-1 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
python-xdg:
  Installed: 0.25-4
  Candidate: 0.25-4
  Version table:
 *** 0.25-4 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
librsvg2-2:
  Installed: 2.40.2-1
  Candidate: 2.40.2-1
  Version table:
 *** 2.40.2-1 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
python-rsvg:
  Installed: 2.32.0+dfsg-3
  Candidate: 2.32.0+dfsg-3
  Version table:
 *** 2.32.0+dfsg-3 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

Any idea?

**Comment by jonls** [comment]
> ```
> ImportError: /usr/lib/python2.7/dist-packages/gi/_gi.so: undefined symbol: _Py_ZeroStruct
> ```

The import error seems to appear in `gi`, the gobject-introspection used for Gtk, Glib, etc. You should probably file a bug report with your distribution as they will be better able to help with this situation. It is unlikely to be related to Redshift in any way.
