### ISSUE TITLE
redshift-gtk fails when using a config file

### ISSUE THREAD

**Issue by sudobkz** [jonls/redshift#367]
##  redshift-gtk -h

```
/usr/lib/python3/dist-packages/redshift_gtk/statusicon.py:33: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GLib, GObject
Traceback (most recent call last):
  File "/usr/bin/redshift-gtk", line 26, in <module>
    from redshift_gtk.statusicon import run
  File "/usr/lib/python3/dist-packages/redshift_gtk/statusicon.py", line 34, in <module>
    gi.require_version('Gtk', '3.0')
```
## ~/.config/reshift.conf

```
; Global settings for redshift
[redshift]
; Set the day and night screen temperatures
temp-day=5700
temp-night=2000

; Enable/Disable a smooth transition between day and night
; 0 will cause a direct change from day to night screen temperature.
; 1 will gradually increase or decrease the screen temperature.
transition=1

; Set the screen brightness. Default is 1.0.
;brightness=0.9
; It is also possible to use different settings for day and night
; since version 1.8.
;brightness-day=0.7
;brightness-night=0.4
; Set the screen gamma (for all colors, or each color channel
; individually)
gamma=0.8
;gamma=0.8:0.7:0.8
; This can also be set individually for day and night since
; version 1.10.
;gamma-day=0.8:0.7:0.8
;gamma-night=0.6

; Set the location-provider: 'geoclue', 'geoclue2', 'manual'
; type 'redshift -l list' to see possible values.
; The location provider settings are in a different section.
location-provider=manual

; Set the adjustment-method: 'randr', 'vidmode'
; type 'redshift -m list' to see all possible values.
; 'randr' is the preferred method, 'vidmode' is an older API.
; but works in some cases when 'randr' does not.
; The adjustment method settings are in a different section.
adjustment-method=randr

; Configuration of the location-provider:
; type 'redshift -l PROVIDER:help' to see the settings.
; ex: 'redshift -l manual:help'
; Keep in mind that longitudes west of Greenwich (e.g. the Americas)
; are negative numbers.
[manual]
lat=38.932942
lon=-9.308855  

; Configuration of the adjustment-method
; type 'redshift -m METHOD:help' to see the settings.
; ex: 'redshift -m randr:help'
; In this example, randr is configured to adjust screen 1.
; Note that the numbering starts from 0, so this is actually the
; second screen. If this option is not specified, Redshift will try
; to adjust _all_ screens.
[randr]
;screen=1
```
## machine

cat /etc/issue:
    Ubuntu 16.04 LTS \n \l

uname -a:
    Linux zoom 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sudobkz** [comment]
I was able to get it working by adding before any other imports

/usr/lib/python3/dist-packages/redshift_gtk/statusicon.py
----------
import gi
gi.require_version('Gtk', '3.0')
gi.require_version('Appindicator3', '3.01')

Also, the full gps coordinates from google maps was not working.  I reduced that to 1 decimal point and it started working.

**Comment by jetimms** [comment]
I'm seeing the same warning, but it's just a warning for me, with an additional warning about AppIndicator3:

**redshift-gtk -h**
```
/usr/lib/python3/dist-packages/redshift_gtk/statusicon.py:32: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GLib, GObject
/usr/lib/python3/dist-packages/redshift_gtk/statusicon.py:35: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator

```

**machine**
<same>

**Comment by jetimms** [comment]
@sudobkz 
Thanks, that worked, except for:
```
gi.require_version('AppIndicator3', '0.1')
```
Instead of:
```
gi.require_version('Appindicator3', '3.01')
```

Have you created a pull request?

**Comment by jonls** [comment]
Thanks for the report. This seems to apply to an older release of Redshift. If you think this is still an issue in the latest release, please reopen.
