### ISSUE TITLE
redshift-gtk is not started

### ISSUE THREAD

**Issue by Stml89** [jonls/redshift#459]
Hello,
I'm trying to start  redshift on arch
Let me know if I can provide more information

```
$ redshift-gtk 
Traceback (most recent call last):
  File "/usr/bin/redshift-gtk", line 26, in <module>
    from redshift_gtk.statusicon import run
  File "/usr/lib/python3.6/site-packages/redshift_gtk/statusicon.py", line 32, in <module>
    import gi
  File "/usr/lib/python3.6/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi'
```
```
$ uname -a
Linux localhost 4.8.10-1-ARCH #1 SMP PREEMPT Mon Nov 21 11:55:43 CET 2016 x86_64 GNU/Linux
```
```
$ redshift -V
redshift 1.11
```
```
$ python --version
Python 3.5.2
```

Could you please help me with this error?

**Comment by Stml89** [comment]
I just update system. Issue is gone.
For now a have:
`Linux localhost 4.10.8-1-ARCH #1 SMP PREEMPT Fri Mar 31 16:50:19 CEST 2017 x86_64 GNU/Linux`
