### ISSUE TITLE
redshift-gtk throws error on start and aborts, on Mint

### ISSUE THREAD

**Issue by CottonEaster** [jonls/redshift#462]
```
~ $ redshift-gtk
Traceback (most recent call last):
  File "/usr/local/bin/redshift-gtk", line 26, in <module>
    from redshift_gtk.statusicon import run
  File "/usr/local/lib/python3.5/site-packages/redshift_gtk/statusicon.py", line 32, in <module>
    import gi
ImportError: No module named 'gi'
```
Reinstalling 'gi' via `apt` or `pip` does not change anything.

Redshift 1.10-5ubuntu1
Mint 18.1 x64 Cinnamon.

**Comment by ACinnamonUserInUK** [comment]
[This report](https://stackoverflow.com/questions/14295680/cannot-import-a-python-module-that-is-definitely-installed-mechanize) of python problems with another program seems very relevant.

**Comment by jonls** [comment]
This seems to be related to missing gobject Python packages. Try to install or reinstall those packages (maybe `python-gobject` or `gobject-introspection`?) if this is still an issue. Since this issue is getting old, I'm going to close it. Please reopen if this is still not solved.

**Comment by CottonEaster** [comment]
I still have this problem - on one (but not the other) of my Mint installations (and Redshift is now bundled with Mint). The fix that jonls was kind enough to suggest seems not to work.

```
~ $ redshift-gtk
Traceback (most recent call last):
  File "/usr/local/bin/redshift-gtk", line 26, in <module>
    from redshift_gtk.statusicon import run
  File "/usr/local/lib/python3.5/site-packages/redshift_gtk/statusicon.py", line 32, in <module>
    import gi
ImportError: No module named 'gi'

~ $ sudo apt install gobject-introspection python-gobject --reinstall
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 to upgrade, 0 to newly install, 2 reinstalled, 0 to remove and 0 not to upgrade.
Need to get 258 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://ubuntu.retrosnub.co.uk/ubuntu xenial/main amd64 gobject-introspection amd64 1.46.0-3ubuntu1 [256 kB]
Get:2 http://ubuntu.retrosnub.co.uk/ubuntu xenial/universe amd64 python-gobject all 3.20.0-0ubuntu1 [2,544 B]
Fetched 258 kB in 0s (981 kB/s)           
(Reading database ... 395563 files and directories currently installed.)
Preparing to unpack .../gobject-introspection_1.46.0-3ubuntu1_amd64.deb ...
Unpacking gobject-introspection (1.46.0-3ubuntu1) over (1.46.0-3ubuntu1) ...
Preparing to unpack .../python-gobject_3.20.0-0ubuntu1_all.deb ...
Unpacking python-gobject (3.20.0-0ubuntu1) over (3.20.0-0ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up gobject-introspection (1.46.0-3ubuntu1) ...
Setting up python-gobject (3.20.0-0ubuntu1) ...
~ $ redshift-gtk
Traceback (most recent call last):
  File "/usr/local/bin/redshift-gtk", line 26, in <module>
    from redshift_gtk.statusicon import run
  File "/usr/local/lib/python3.5/site-packages/redshift_gtk/statusicon.py", line 32, in <module>
    import gi
ImportError: No module named 'gi'
```
