### ISSUE TITLE
Cannot launch redshift-gtk (Arch Linux)

### ISSUE THREAD

**Issue by kepler2** [jonls/redshift#492]
Hello!

I'm having difficulties in starting redshift-gtk.

Installed it from AUR - redshift-gtk-git, python-gobject, python-xdg, python2-xdg.

Here is the terminal output:

Linux 4.12.4-1-ARCH x86_64

```
Traceback (most recent call last):
  File "/usr/bin/redshift-gtk", line 27, in <module>
    run()
  File "/usr/lib/python3.6/site-packages/redshift_gtk/statusicon.py", line 362, in run
    RedshiftStatusIcon(c)
  File "/usr/lib/python3.6/site-packages/redshift_gtk/statusicon.py", line 93, in __init__
    autostart_item.set_active(utils.get_autostart())
  File "/usr/lib/python3.6/site-packages/redshift_gtk/utils.py", line 71, in get_autostart
    dfile, path = open_autostart_file()
  File "/usr/lib/python3.6/site-packages/redshift_gtk/utils.py", line 39, in open_autostart_file
    autostart_dir = xdg.BaseDirectory.save_config_path("autostart")
AttributeError: module 'xdg' has no attribute 'BaseDirectory'
```

Any advice? 
Thanks :)

**Comment by jonls** [comment]
Thanks 👍  Should be fixed now.

**Comment by kepler2** [comment]
I thank you. It launches properly in a WM, will try on my PC later and report back.
nd report back

**Comment by kepler2** [comment]
Also works on PC. Thanks!
