### ISSUE TITLE
Not open with this error

### ISSUE THREAD

**Issue by robsonsilv4** [jonls/redshift#561]
Traceback (most recent call last):
  File "/usr/bin/redshift-gtk", line 26, in <module>
    from redshift_gtk.statusicon import run
  File "/usr/lib/python3.6/site-packages/redshift_gtk/statusicon.py", line 44, in <module>
    from . import utils
  File "/usr/lib/python3.6/site-packages/redshift_gtk/utils.py", line 23, in <module>
    from xdg import BaseDirectory as base
ModuleNotFoundError: No module named 'xdg'

**Comment by jonls** [comment]
Install the xdg module. If you installed Redshift from packages provided by your distribution, you should contact your distribution and ask them to install the correct dependencies.

**Comment by tremby** [comment]
I just had the same error. It seems the version of the xdg module installed for python3.6 has no `BaseDirectory` in it.

**Comment by tremby** [comment]
I think redshift-gtk wants this package https://pypi.org/project/pyxdg/
while in python3 if you install `xdg` you get this package https://pypi.org/project/xdg/

**Comment by tremby** [comment]
In my case, the solution was `pip3 uninstall xdg`.
I then tried `pip3 install pyxdg` but I was told it was already installed (maybe from a system package?), and sure enough, redshift-gtk now runs agani.
