### ISSUE TITLE
[BUG] redshift-gtk fails on start

### ISSUE THREAD

**Issue by JanKaifer** [jonls/redshift#615]
I've just installed redshift. redshift itself runs fine but redshift-gtk throws following error:
```
pearman@pearbook ~> redshift-gtk 
Traceback (most recent call last):
  File "/usr/bin/redshift-gtk", line 26, in <module>
    from redshift_gtk.statusicon import run
  File "/usr/lib/python3.6/site-packages/redshift_gtk/statusicon.py", line 33, in <module>
    gi.require_version('Gtk', '3.0')
AttributeError: module 'gi' has no attribute 'require_version'
```

I run arch linux wuth KDE. here is GTK versions:
```
pearman@pearbook ~> pacman -Q gtk3 gtk2
gtk3 3.22.30-1
gtk2 2.24.32-1
```

**Comment by kakurasan** [comment]
Is `python-gobject` installed? What does `/usr/lib/python3.6/site-packages/gi` contain?

**Comment by JanKaifer** [comment]
Package python-gobject is not installed and about `gi`:
```
$ tree /usr/lib/python3.6/site-packages/gi/
/usr/lib/python3.6/site-packages/gi/
└── overrides
    ├── Accounts.py
    ├── BlockDev.py
    ├── IBus.py
    ├── __pycache__
    │   ├── Accounts.cpython-36.opt-1.pyc
    │   ├── Accounts.cpython-36.pyc
    │   ├── IBus.cpython-36.opt-1.pyc
    │   ├── IBus.cpython-36.pyc
    │   ├── Signon.cpython-36.opt-1.pyc
    │   └── Signon.cpython-36.pyc
    └── Signon.py

2 directories, 10 files
```
