### ISSUE TITLE
Can't start redshift-gtk on Arch

### ISSUE THREAD

**Issue by HaleTom** [jonls/redshift#619]
```
** (process:13455): WARNING **: Failed to load shared library 'libpango-1.0.so.0' referenced by the typelib: /usr/lib/libpango-1.0.so.0: undefined symbol: g_log_structured_standard
Traceback (most recent call last):
  File "/usr/bin/redshift-gtk", line 26, in <module>
    from redshift_gtk.statusicon import run
  File "/usr/lib/python3.6/site-packages/redshift_gtk/statusicon.py", line 35, in <module>
    from gi.repository import Gtk, GLib, GObject
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/lib/python3.6/site-packages/gi/importer.py", line 145, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/home/ravi/.local/share/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/lib/python3.6/site-packages/gi/importer.py", line 145, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/home/ravi/.local/share/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/lib/python3.6/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python3.6/site-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/home/ravi/.local/share/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.6/site-packages/gi/overrides/Pango.py", line 41, in <module>
    FontDescription = override(FontDescription)
  File "/usr/lib/python3.6/site-packages/gi/overrides/__init__.py", line 202, in override
    assert g_type != TYPE_NONE
AssertionError
```

**Comment by jonls** [comment]
This looks like an issue with your install of gobject or python-gobject unrelated to redshift. Maybe pango is not installed? Please report this to Arch.

**Comment by grmat** [comment]
Just some additional info for @HaleTom:

The following optional dependencies are listed for redshift-gtk, ensure you have those installed:

- gtk3 (optional) - for redshift-gtk
- python-gobject (optional) - for redshift-gtk
- python-xdg (optional) - for redshift-gtk 

Next time you experience a packaging issue, visit the [Arch package page](https://www.archlinux.org/packages/community/x86_64/redshift/) and report a bug [there](https://bugs.archlinux.org/?project=5&string=redshift)
