### ISSUE TITLE
Unable to run redshift-gtk

### ISSUE THREAD

**Issue by SethGower** [jonls/redshift#653]
**Describe the bug**
I am unable to run `redshift-gtk` on my new install, but can on my laptop (which has been installed for a while). I am getting the error 

```
Traceback (most recent call last):
  File "/usr/bin/redshift-gtk", line 26, in <module>
    from redshift_gtk.statusicon import run
  File "/usr/lib/python3.7/site-packages/redshift_gtk/statusicon.py", line 31, in <module>
    gi.require_version('Gtk', '3.0')
AttributeError: module 'gi' has no attribute 'require_version'
```

- [x] [I have checked the FAQ](https://github.com/jonls/redshift/blob/master/README.md#faq) and my issue is not mention there.

**To Reproduce**
I honestly don't know. I just run `redshift-gtk` and it fails. `redshift` works perfectly.

**Expected behavior**
`redshift` to run but with a status icon

**Error output/logs/screenshots**
```
Traceback (most recent call last):
  File "/usr/bin/redshift-gtk", line 26, in <module>
    from redshift_gtk.statusicon import run
  File "/usr/lib/python3.7/site-packages/redshift_gtk/statusicon.py", line 31, in <module>
    gi.require_version('Gtk', '3.0')
AttributeError: module 'gi' has no attribute 'require_version'
```
**Software versions (please complete the following information):**
 - OS: `Linux odyssey 4.17.14-arch1-1-ARCH #1 SMP PREEMPT Thu Aug 9 11:56:50 UTC 2018 x86_64 GNU/Linux` (output of `uname -a`)
 - Redshift version: `redshift 1.12`
 - Distribution: Arch Linux
 - Redshift installed from: `sudo pacman -S redshift`

**Comment by SethGower** [comment]
I feel really stupid, but I figured out the problem. I didn't have `python-gobject` installed, I only had `python2-gobject` and `python2-gobject2` installed. Once installing `python-gobject`, `redshift-gtk` worked
