### ISSUE TITLE
Cannot import _gi [circular dependency error when running redshift gt ]

### ISSUE THREAD

**Issue by madrigal1** [jonls/redshift#842]
![image](https://user-images.githubusercontent.com/30615210/134886170-2ed89ac0-1fe8-4ba0-8bc4-4651a3f5016c.png)

**Comment by reitzig** [comment]
Did you ever find a solution to this?

```
❯ redshift-gtk --help
Traceback (most recent call last):
  File "/usr/bin/redshift-gtk", line 26, in <module>
    from redshift_gtk.statusicon import run
  File "/usr/lib/python3.12/site-packages/redshift_gtk/statusicon.py", line 30, in <module>
    import gi
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/gi/__init__.py)
```

Started happening to me after updated a bunch of system packages, hard to narrow down what might have caused it.
